altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  739e37c6-190a-41d3-9803-1024ac487fd8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-12T21:57:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0da41e8f-695b-4253-8d8c-62ea811f98f4
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-03-12T22:00:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: f34ac2b5-035c-40fe-80b4-277bc3911dbb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T22:00:14+00:00'
            elementCondition: null
            fieldUid: cf83c8fd-a311-41ab-8250-a4950a149f6d # Cloudflare Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44994a94-8a87-46d1-8127-f6882d1feaf0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1ea056a2-a3da-4a1e-b391-69fc58f7d933
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: /transforms
