dateModified: 1741818029
email:
  fromEmail: mck247@gmail.com
  fromName: mck-portfolio
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
meta:
  __names__:
    1f3fb01e-8cf9-4f43-a506-2f71468df0ed: Portfolio # Portfolio
    8b791e8b-5c63-4fa0-8152-1948e73f2cc6: 'Main Image' # Main Image
    47c96c33-bfd0-461d-be6d-02f5e52fa448: 'Project Summary' # Project Summary
    60afd7fb-2f52-4c86-9ae9-e5e48dd045a4: Portfolio # Portfolio
    78a82d0c-8b84-47b5-9d27-3ce8f342a951: 'Project Images' # Project Images
    1445dbd5-ccef-4fa3-9056-0b8415192dc8: Home # Home
    1995c984-7976-460c-957a-bf9dcdcc7ed6: Home # Home
    9171106b-0dd1-4f50-866a-16cb06075f29: mck-portfolio # mck-portfolio
    adc00353-c591-4ccc-b163-e71f6d107da9: mck-portfolio # mck-portfolio
    bde027f6-27be-4d50-89fb-9f3a4a622559: Simple # Simple
    cf83c8fd-a311-41ab-8250-a4950a149f6d: 'Cloudflare Code' # Cloudflare Code
    e84480ee-4abb-457c-beb5-c36dd5fee591: Images # Images
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: mck-portfolio
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
