fieldLayouts:
  6c80adc0-98f7-4e61-af3a-a2005eb434e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-13T21:18:07+00:00'
            elementCondition: null
            fieldUid: b7d11927-833c-4c91-bb04-75361058ee4a # Icon Logo Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98fab734-d79e-4b13-99d9-d543a08a052c
            userCondition: null
            warning: null
            width: 100
        name: Nvaigation
        uid: 5c79d6cc-3a02-45f9-9baa-1cd4ca313ebb
        userCondition: null
handle: globals
name: Globals
sortOrder: 1
