defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1f3fb01e-8cf9-4f43-a506-2f71468df0ed # Portfolio
handle: portfolio
maxAuthors: 1
name: Portfolio
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  adc00353-c591-4ccc-b163-e71f6d107da9: # mck-portfolio
    enabledByDefault: true
    hasUrls: true
    template: _portfolio/entry.twig
    uriFormat: 'portfolio/{slug}'
structure:
  maxLevels: null
  uid: e66446f2-f219-4295-97ed-400c10223126
type: structure
